default: &default
  adapter: postgresql
  username: solr_notes
  password: solr_notes
  encoding: unicode
  host: localhost
  min_messages: WARNING

development:
  <<: *default
  database: solr_notes_development

test:
  <<: *default
  database: solr_notes_test

production:
  <<: *default
  database: solr_notes_production
